/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Value = IDL.Rec();
export const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _ImmutableObjectStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _ImmutableObjectStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const PrydoIdRecord = IDL.Record({
  'avatarType' : IDL.Text,
  'tier' : IDL.Text,
  'timestamp' : IDL.Int,
  'wallet' : IDL.Text,
});
export const PrydoIdWithPhoto = IDL.Record({
  'photo' : IDL.Opt(ExternalBlob),
  'idRecord' : PrydoIdRecord,
});
export const PrydoIdWithTokenId = IDL.Record({
  'tokenId' : IDL.Opt(IDL.Nat),
  'photo' : IDL.Opt(ExternalBlob),
  'idRecord' : PrydoIdRecord,
});
export const FraudFlag = IDL.Record({
  'status' : IDL.Text,
  'refereeWallet' : IDL.Text,
  'flagReason' : IDL.Text,
  'timestamp' : IDL.Int,
  'severity' : IDL.Text,
  'referrerWallet' : IDL.Text,
});
export const ChallengeType = IDL.Variant({
  'smile' : IDL.Null,
  'blink' : IDL.Null,
});
export const LivenessAttempt = IDL.Record({
  'attempted_at' : IDL.Int,
  'passed' : IDL.Bool,
  'challenge_type' : ChallengeType,
});
export const LivenessStatus = IDL.Record({
  'cooldown_until' : IDL.Opt(IDL.Int),
  'retry_count' : IDL.Nat,
  'attempts' : IDL.Vec(LivenessAttempt),
});
export const MintInfo = IDL.Record({
  'tokenId' : IDL.Nat,
  'mintTimestamp' : IDL.Int,
  'blockIndex' : IDL.Nat,
  'wallet' : IDL.Text,
});
export const ReferralRecord = IDL.Record({
  'referrer' : IDL.Text,
  'blockId' : IDL.Nat,
  'timestamp' : IDL.Int,
  'ipHash' : IDL.Text,
  'deviceHash' : IDL.Text,
  'referee' : IDL.Text,
});
export const VerificationStatus = IDL.Variant({
  'FAIL' : IDL.Null,
  'PASS' : IDL.Null,
  'UNVERIFIED' : IDL.Null,
  'PENDING' : IDL.Null,
});
export const IdDocumentType = IDL.Variant({
  'Passport' : IDL.Null,
  'Aadhaar' : IDL.Null,
  'DriversLicense' : IDL.Null,
  'NationalId' : IDL.Null,
});
export const VerificationRecord = IDL.Record({
  'status' : VerificationStatus,
  'liveness_retry_count' : IDL.Opt(IDL.Nat),
  'liveness_attempts' : IDL.Opt(IDL.Vec(LivenessAttempt)),
  'id_document_type' : IDL.Opt(IdDocumentType),
  'error_reason' : IDL.Opt(IDL.Text),
  'liveness_cooldown_until' : IDL.Opt(IDL.Int),
  'verified_at' : IDL.Int,
  'wallet' : IDL.Text,
});
Value.fill(
  IDL.Variant({
    'Int' : IDL.Int,
    'Map' : IDL.Vec(IDL.Tuple(IDL.Text, Value)),
    'Nat' : IDL.Nat,
    'Blob' : IDL.Vec(IDL.Nat8),
    'Bool' : IDL.Bool,
    'Text' : IDL.Text,
    'Array' : IDL.Vec(Value),
  })
);
export const ArchivedBlocksRange = IDL.Record({
  'start' : IDL.Nat,
  'length' : IDL.Nat,
});
export const DataCertificate = IDL.Record({
  'certificate' : IDL.Vec(IDL.Nat8),
  'hash_tree' : IDL.Vec(IDL.Nat8),
});
export const Account = IDL.Record({
  'owner' : IDL.Principal,
  'subaccount' : IDL.Opt(IDL.Vec(IDL.Nat8)),
});
export const TransferArg = IDL.Record({
  'to' : Account,
  'token_id' : IDL.Nat,
  'memo' : IDL.Opt(IDL.Vec(IDL.Nat8)),
  'from_subaccount' : IDL.Opt(IDL.Vec(IDL.Nat8)),
  'created_at_time' : IDL.Opt(IDL.Nat),
});
export const TransferError = IDL.Variant({
  'GenericError' : IDL.Record({ 'message' : IDL.Text, 'error_code' : IDL.Nat }),
  'Duplicate' : IDL.Record({ 'duplicate_of' : IDL.Nat }),
  'NonExistingTokenId' : IDL.Null,
  'Unauthorized' : IDL.Null,
  'CreatedInFuture' : IDL.Record({ 'ledger_time' : IDL.Nat }),
  'InvalidRecipient' : IDL.Null,
  'GenericBatchError' : IDL.Record({
    'message' : IDL.Text,
    'error_code' : IDL.Nat,
  }),
  'TooOld' : IDL.Null,
});
export const TransferResult = IDL.Variant({
  'Ok' : IDL.Nat,
  'Err' : TransferError,
});
export const MintOutput = IDL.Record({
  'idCount' : IDL.Nat,
  'record' : PrydoIdWithPhoto,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const VerificationResult = IDL.Variant({
  'ok' : VerificationRecord,
  'err' : IDL.Text,
});

export const idlService = IDL.Service({
  '_immutableObjectStorageBlobsAreLive' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [IDL.Vec(IDL.Bool)],
      ['query'],
    ),
  '_immutableObjectStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_immutableObjectStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_ImmutableObjectStorageCreateCertificateResult],
      [],
    ),
  '_immutableObjectStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
      [_ImmutableObjectStorageRefillResult],
      [],
    ),
  '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  'addReferral' : IDL.Func([IDL.Text, IDL.Text, IDL.Text, IDL.Text], [], []),
  'clearAllIds' : IDL.Func([], [IDL.Nat], []),
  'generateReferralCode' : IDL.Func([IDL.Text], [IDL.Text], ['query']),
  'getAllMintedIds' : IDL.Func([], [IDL.Vec(PrydoIdWithPhoto)], ['query']),
  'getAllMintedIdsWithTokenIds' : IDL.Func(
      [],
      [IDL.Vec(PrydoIdWithTokenId)],
      ['query'],
    ),
  'getFraudFlags' : IDL.Func([], [IDL.Vec(FraudFlag)], ['query']),
  'getIdByWallet' : IDL.Func([IDL.Text], [PrydoIdWithPhoto], ['query']),
  'getIdCount' : IDL.Func([], [IDL.Nat], ['query']),
  'getLivenessStatus' : IDL.Func([IDL.Text], [LivenessStatus], ['query']),
  'getMintInfoByWallet' : IDL.Func([IDL.Text], [IDL.Opt(MintInfo)], ['query']),
  'getMintedCount' : IDL.Func([], [IDL.Nat], ['query']),
  'getReferralsByWallet' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(ReferralRecord)],
      ['query'],
    ),
  'getVerificationStatus' : IDL.Func(
      [IDL.Text],
      [VerificationRecord],
      ['query'],
    ),
  'icrc3_get_blocks' : IDL.Func(
      [IDL.Vec(IDL.Record({ 'start' : IDL.Nat, 'length' : IDL.Nat }))],
      [
        IDL.Record({
          'log_length' : IDL.Nat,
          'blocks' : IDL.Vec(IDL.Record({ 'id' : IDL.Nat, 'block' : Value })),
          'archived_blocks' : IDL.Vec(ArchivedBlocksRange),
        }),
      ],
      ['query'],
    ),
  'icrc3_get_tip_certificate' : IDL.Func(
      [],
      [IDL.Opt(DataCertificate)],
      ['query'],
    ),
  'icrc3_supported_block_types' : IDL.Func(
      [],
      [IDL.Vec(IDL.Record({ 'url' : IDL.Text, 'block_type' : IDL.Text }))],
      ['query'],
    ),
  'icrc7_atomic_batch_transfers' : IDL.Func([], [IDL.Opt(IDL.Bool)], ['query']),
  'icrc7_balance_of' : IDL.Func(
      [IDL.Vec(Account)],
      [IDL.Vec(IDL.Nat)],
      ['query'],
    ),
  'icrc7_collection_metadata' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Text, Value))],
      ['query'],
    ),
  'icrc7_default_take_value' : IDL.Func([], [IDL.Opt(IDL.Nat)], ['query']),
  'icrc7_description' : IDL.Func([], [IDL.Opt(IDL.Text)], ['query']),
  'icrc7_logo' : IDL.Func([], [IDL.Opt(IDL.Text)], ['query']),
  'icrc7_max_memo_size' : IDL.Func([], [IDL.Opt(IDL.Nat)], ['query']),
  'icrc7_max_query_batch_size' : IDL.Func([], [IDL.Opt(IDL.Nat)], ['query']),
  'icrc7_max_take_value' : IDL.Func([], [IDL.Opt(IDL.Nat)], ['query']),
  'icrc7_max_update_batch_size' : IDL.Func([], [IDL.Opt(IDL.Nat)], ['query']),
  'icrc7_name' : IDL.Func([], [IDL.Text], ['query']),
  'icrc7_owner_of' : IDL.Func(
      [IDL.Vec(IDL.Nat)],
      [IDL.Vec(IDL.Opt(Account))],
      ['query'],
    ),
  'icrc7_supply_cap' : IDL.Func([], [IDL.Opt(IDL.Nat)], ['query']),
  'icrc7_symbol' : IDL.Func([], [IDL.Text], ['query']),
  'icrc7_token_metadata' : IDL.Func(
      [IDL.Vec(IDL.Nat)],
      [IDL.Vec(IDL.Opt(IDL.Vec(IDL.Tuple(IDL.Text, Value))))],
      ['query'],
    ),
  'icrc7_tokens' : IDL.Func(
      [IDL.Opt(IDL.Nat), IDL.Opt(IDL.Nat)],
      [IDL.Vec(IDL.Nat)],
      ['query'],
    ),
  'icrc7_tokens_of' : IDL.Func(
      [Account, IDL.Opt(IDL.Nat), IDL.Opt(IDL.Nat)],
      [IDL.Vec(IDL.Nat)],
      ['query'],
    ),
  'icrc7_total_supply' : IDL.Func([], [IDL.Nat], ['query']),
  'icrc7_transfer' : IDL.Func(
      [IDL.Vec(TransferArg)],
      [IDL.Vec(IDL.Opt(TransferResult))],
      [],
    ),
  'mintId' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Opt(ExternalBlob)],
      [MintOutput],
      [],
    ),
  'reVerifyIdentity' : IDL.Func([IDL.Text], [IDL.Text], []),
  'removeId' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'updateFlagStatus' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Int, IDL.Text],
      [IDL.Bool],
      [],
    ),
  'uploadPhoto' : IDL.Func([IDL.Text, ExternalBlob], [PrydoIdWithPhoto], []),
  'verifyIdentity' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IdDocumentType,
        IDL.Vec(IDL.Tuple(IDL.Text, IDL.Bool)),
      ],
      [VerificationResult],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Value = IDL.Rec();
  const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _ImmutableObjectStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _ImmutableObjectStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const PrydoIdRecord = IDL.Record({
    'avatarType' : IDL.Text,
    'tier' : IDL.Text,
    'timestamp' : IDL.Int,
    'wallet' : IDL.Text,
  });
  const PrydoIdWithPhoto = IDL.Record({
    'photo' : IDL.Opt(ExternalBlob),
    'idRecord' : PrydoIdRecord,
  });
  const PrydoIdWithTokenId = IDL.Record({
    'tokenId' : IDL.Opt(IDL.Nat),
    'photo' : IDL.Opt(ExternalBlob),
    'idRecord' : PrydoIdRecord,
  });
  const FraudFlag = IDL.Record({
    'status' : IDL.Text,
    'refereeWallet' : IDL.Text,
    'flagReason' : IDL.Text,
    'timestamp' : IDL.Int,
    'severity' : IDL.Text,
    'referrerWallet' : IDL.Text,
  });
  const ChallengeType = IDL.Variant({ 'smile' : IDL.Null, 'blink' : IDL.Null });
  const LivenessAttempt = IDL.Record({
    'attempted_at' : IDL.Int,
    'passed' : IDL.Bool,
    'challenge_type' : ChallengeType,
  });
  const LivenessStatus = IDL.Record({
    'cooldown_until' : IDL.Opt(IDL.Int),
    'retry_count' : IDL.Nat,
    'attempts' : IDL.Vec(LivenessAttempt),
  });
  const MintInfo = IDL.Record({
    'tokenId' : IDL.Nat,
    'mintTimestamp' : IDL.Int,
    'blockIndex' : IDL.Nat,
    'wallet' : IDL.Text,
  });
  const ReferralRecord = IDL.Record({
    'referrer' : IDL.Text,
    'blockId' : IDL.Nat,
    'timestamp' : IDL.Int,
    'ipHash' : IDL.Text,
    'deviceHash' : IDL.Text,
    'referee' : IDL.Text,
  });
  const VerificationStatus = IDL.Variant({
    'FAIL' : IDL.Null,
    'PASS' : IDL.Null,
    'UNVERIFIED' : IDL.Null,
    'PENDING' : IDL.Null,
  });
  const IdDocumentType = IDL.Variant({
    'Passport' : IDL.Null,
    'Aadhaar' : IDL.Null,
    'DriversLicense' : IDL.Null,
    'NationalId' : IDL.Null,
  });
  const VerificationRecord = IDL.Record({
    'status' : VerificationStatus,
    'liveness_retry_count' : IDL.Opt(IDL.Nat),
    'liveness_attempts' : IDL.Opt(IDL.Vec(LivenessAttempt)),
    'id_document_type' : IDL.Opt(IdDocumentType),
    'error_reason' : IDL.Opt(IDL.Text),
    'liveness_cooldown_until' : IDL.Opt(IDL.Int),
    'verified_at' : IDL.Int,
    'wallet' : IDL.Text,
  });
  Value.fill(
    IDL.Variant({
      'Int' : IDL.Int,
      'Map' : IDL.Vec(IDL.Tuple(IDL.Text, Value)),
      'Nat' : IDL.Nat,
      'Blob' : IDL.Vec(IDL.Nat8),
      'Bool' : IDL.Bool,
      'Text' : IDL.Text,
      'Array' : IDL.Vec(Value),
    })
  );
  const ArchivedBlocksRange = IDL.Record({
    'start' : IDL.Nat,
    'length' : IDL.Nat,
  });
  const DataCertificate = IDL.Record({
    'certificate' : IDL.Vec(IDL.Nat8),
    'hash_tree' : IDL.Vec(IDL.Nat8),
  });
  const Account = IDL.Record({
    'owner' : IDL.Principal,
    'subaccount' : IDL.Opt(IDL.Vec(IDL.Nat8)),
  });
  const TransferArg = IDL.Record({
    'to' : Account,
    'token_id' : IDL.Nat,
    'memo' : IDL.Opt(IDL.Vec(IDL.Nat8)),
    'from_subaccount' : IDL.Opt(IDL.Vec(IDL.Nat8)),
    'created_at_time' : IDL.Opt(IDL.Nat),
  });
  const TransferError = IDL.Variant({
    'GenericError' : IDL.Record({
      'message' : IDL.Text,
      'error_code' : IDL.Nat,
    }),
    'Duplicate' : IDL.Record({ 'duplicate_of' : IDL.Nat }),
    'NonExistingTokenId' : IDL.Null,
    'Unauthorized' : IDL.Null,
    'CreatedInFuture' : IDL.Record({ 'ledger_time' : IDL.Nat }),
    'InvalidRecipient' : IDL.Null,
    'GenericBatchError' : IDL.Record({
      'message' : IDL.Text,
      'error_code' : IDL.Nat,
    }),
    'TooOld' : IDL.Null,
  });
  const TransferResult = IDL.Variant({ 'Ok' : IDL.Nat, 'Err' : TransferError });
  const MintOutput = IDL.Record({
    'idCount' : IDL.Nat,
    'record' : PrydoIdWithPhoto,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const VerificationResult = IDL.Variant({
    'ok' : VerificationRecord,
    'err' : IDL.Text,
  });
  
  return IDL.Service({
    '_immutableObjectStorageBlobsAreLive' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [IDL.Vec(IDL.Bool)],
        ['query'],
      ),
    '_immutableObjectStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_immutableObjectStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_ImmutableObjectStorageCreateCertificateResult],
        [],
      ),
    '_immutableObjectStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
        [_ImmutableObjectStorageRefillResult],
        [],
      ),
    '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    'addReferral' : IDL.Func([IDL.Text, IDL.Text, IDL.Text, IDL.Text], [], []),
    'clearAllIds' : IDL.Func([], [IDL.Nat], []),
    'generateReferralCode' : IDL.Func([IDL.Text], [IDL.Text], ['query']),
    'getAllMintedIds' : IDL.Func([], [IDL.Vec(PrydoIdWithPhoto)], ['query']),
    'getAllMintedIdsWithTokenIds' : IDL.Func(
        [],
        [IDL.Vec(PrydoIdWithTokenId)],
        ['query'],
      ),
    'getFraudFlags' : IDL.Func([], [IDL.Vec(FraudFlag)], ['query']),
    'getIdByWallet' : IDL.Func([IDL.Text], [PrydoIdWithPhoto], ['query']),
    'getIdCount' : IDL.Func([], [IDL.Nat], ['query']),
    'getLivenessStatus' : IDL.Func([IDL.Text], [LivenessStatus], ['query']),
    'getMintInfoByWallet' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(MintInfo)],
        ['query'],
      ),
    'getMintedCount' : IDL.Func([], [IDL.Nat], ['query']),
    'getReferralsByWallet' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(ReferralRecord)],
        ['query'],
      ),
    'getVerificationStatus' : IDL.Func(
        [IDL.Text],
        [VerificationRecord],
        ['query'],
      ),
    'icrc3_get_blocks' : IDL.Func(
        [IDL.Vec(IDL.Record({ 'start' : IDL.Nat, 'length' : IDL.Nat }))],
        [
          IDL.Record({
            'log_length' : IDL.Nat,
            'blocks' : IDL.Vec(IDL.Record({ 'id' : IDL.Nat, 'block' : Value })),
            'archived_blocks' : IDL.Vec(ArchivedBlocksRange),
          }),
        ],
        ['query'],
      ),
    'icrc3_get_tip_certificate' : IDL.Func(
        [],
        [IDL.Opt(DataCertificate)],
        ['query'],
      ),
    'icrc3_supported_block_types' : IDL.Func(
        [],
        [IDL.Vec(IDL.Record({ 'url' : IDL.Text, 'block_type' : IDL.Text }))],
        ['query'],
      ),
    'icrc7_atomic_batch_transfers' : IDL.Func(
        [],
        [IDL.Opt(IDL.Bool)],
        ['query'],
      ),
    'icrc7_balance_of' : IDL.Func(
        [IDL.Vec(Account)],
        [IDL.Vec(IDL.Nat)],
        ['query'],
      ),
    'icrc7_collection_metadata' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Text, Value))],
        ['query'],
      ),
    'icrc7_default_take_value' : IDL.Func([], [IDL.Opt(IDL.Nat)], ['query']),
    'icrc7_description' : IDL.Func([], [IDL.Opt(IDL.Text)], ['query']),
    'icrc7_logo' : IDL.Func([], [IDL.Opt(IDL.Text)], ['query']),
    'icrc7_max_memo_size' : IDL.Func([], [IDL.Opt(IDL.Nat)], ['query']),
    'icrc7_max_query_batch_size' : IDL.Func([], [IDL.Opt(IDL.Nat)], ['query']),
    'icrc7_max_take_value' : IDL.Func([], [IDL.Opt(IDL.Nat)], ['query']),
    'icrc7_max_update_batch_size' : IDL.Func([], [IDL.Opt(IDL.Nat)], ['query']),
    'icrc7_name' : IDL.Func([], [IDL.Text], ['query']),
    'icrc7_owner_of' : IDL.Func(
        [IDL.Vec(IDL.Nat)],
        [IDL.Vec(IDL.Opt(Account))],
        ['query'],
      ),
    'icrc7_supply_cap' : IDL.Func([], [IDL.Opt(IDL.Nat)], ['query']),
    'icrc7_symbol' : IDL.Func([], [IDL.Text], ['query']),
    'icrc7_token_metadata' : IDL.Func(
        [IDL.Vec(IDL.Nat)],
        [IDL.Vec(IDL.Opt(IDL.Vec(IDL.Tuple(IDL.Text, Value))))],
        ['query'],
      ),
    'icrc7_tokens' : IDL.Func(
        [IDL.Opt(IDL.Nat), IDL.Opt(IDL.Nat)],
        [IDL.Vec(IDL.Nat)],
        ['query'],
      ),
    'icrc7_tokens_of' : IDL.Func(
        [Account, IDL.Opt(IDL.Nat), IDL.Opt(IDL.Nat)],
        [IDL.Vec(IDL.Nat)],
        ['query'],
      ),
    'icrc7_total_supply' : IDL.Func([], [IDL.Nat], ['query']),
    'icrc7_transfer' : IDL.Func(
        [IDL.Vec(TransferArg)],
        [IDL.Vec(IDL.Opt(TransferResult))],
        [],
      ),
    'mintId' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Opt(ExternalBlob)],
        [MintOutput],
        [],
      ),
    'reVerifyIdentity' : IDL.Func([IDL.Text], [IDL.Text], []),
    'removeId' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'updateFlagStatus' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Int, IDL.Text],
        [IDL.Bool],
        [],
      ),
    'uploadPhoto' : IDL.Func([IDL.Text, ExternalBlob], [PrydoIdWithPhoto], []),
    'verifyIdentity' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IdDocumentType,
          IDL.Vec(IDL.Tuple(IDL.Text, IDL.Bool)),
        ],
        [VerificationResult],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };