/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Account {
  'owner' : Principal,
  'subaccount' : [] | [Uint8Array],
}
export interface ArchivedBlocksRange { 'start' : bigint, 'length' : bigint }
export type ChallengeType = { 'smile' : null } |
  { 'blink' : null };
export interface DataCertificate {
  'certificate' : Uint8Array,
  'hash_tree' : Uint8Array,
}
export type ExternalBlob = Uint8Array;
export interface FraudFlag {
  'status' : string,
  'refereeWallet' : string,
  'flagReason' : string,
  'timestamp' : bigint,
  'severity' : string,
  'referrerWallet' : string,
}
export type IdDocumentType = { 'Passport' : null } |
  { 'Aadhaar' : null } |
  { 'DriversLicense' : null } |
  { 'NationalId' : null };
export interface LivenessAttempt {
  'attempted_at' : bigint,
  'passed' : boolean,
  'challenge_type' : ChallengeType,
}
export interface LivenessStatus {
  'cooldown_until' : [] | [bigint],
  'retry_count' : bigint,
  'attempts' : Array<LivenessAttempt>,
}
export interface MintInfo {
  'tokenId' : bigint,
  'mintTimestamp' : bigint,
  'blockIndex' : bigint,
  'wallet' : string,
}
export interface MintOutput { 'idCount' : bigint, 'record' : PrydoIdWithPhoto }
export interface PrydoIdRecord {
  'avatarType' : string,
  'tier' : string,
  'timestamp' : bigint,
  'wallet' : string,
}
export interface PrydoIdWithPhoto {
  'photo' : [] | [ExternalBlob],
  'idRecord' : PrydoIdRecord,
}
export interface PrydoIdWithTokenId {
  'tokenId' : [] | [bigint],
  'photo' : [] | [ExternalBlob],
  'idRecord' : PrydoIdRecord,
}
export interface ReferralRecord {
  'referrer' : string,
  'blockId' : bigint,
  'timestamp' : bigint,
  'ipHash' : string,
  'deviceHash' : string,
  'referee' : string,
}
export interface TransferArg {
  'to' : Account,
  'token_id' : bigint,
  'memo' : [] | [Uint8Array],
  'from_subaccount' : [] | [Uint8Array],
  'created_at_time' : [] | [bigint],
}
export type TransferError = {
    'GenericError' : { 'message' : string, 'error_code' : bigint }
  } |
  { 'Duplicate' : { 'duplicate_of' : bigint } } |
  { 'NonExistingTokenId' : null } |
  { 'Unauthorized' : null } |
  { 'CreatedInFuture' : { 'ledger_time' : bigint } } |
  { 'InvalidRecipient' : null } |
  { 'GenericBatchError' : { 'message' : string, 'error_code' : bigint } } |
  { 'TooOld' : null };
export type TransferResult = { 'Ok' : bigint } |
  { 'Err' : TransferError };
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export type Value = { 'Int' : bigint } |
  { 'Map' : Array<[string, Value]> } |
  { 'Nat' : bigint } |
  { 'Blob' : Uint8Array } |
  { 'Bool' : boolean } |
  { 'Text' : string } |
  { 'Array' : Array<Value> };
export interface VerificationRecord {
  'status' : VerificationStatus,
  'liveness_retry_count' : [] | [bigint],
  'liveness_attempts' : [] | [Array<LivenessAttempt>],
  'id_document_type' : [] | [IdDocumentType],
  'error_reason' : [] | [string],
  'liveness_cooldown_until' : [] | [bigint],
  'verified_at' : bigint,
  'wallet' : string,
}
export type VerificationResult = { 'ok' : VerificationRecord } |
  { 'err' : string };
export type VerificationStatus = { 'FAIL' : null } |
  { 'PASS' : null } |
  { 'UNVERIFIED' : null } |
  { 'PENDING' : null };
export interface _ImmutableObjectStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _ImmutableObjectStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _ImmutableObjectStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_immutableObjectStorageBlobsAreLive' : ActorMethod<
    [Array<Uint8Array>],
    Array<boolean>
  >,
  '_immutableObjectStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_immutableObjectStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_immutableObjectStorageCreateCertificate' : ActorMethod<
    [string],
    _ImmutableObjectStorageCreateCertificateResult
  >,
  '_immutableObjectStorageRefillCashier' : ActorMethod<
    [[] | [_ImmutableObjectStorageRefillInformation]],
    _ImmutableObjectStorageRefillResult
  >,
  '_immutableObjectStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  'addReferral' : ActorMethod<[string, string, string, string], undefined>,
  'clearAllIds' : ActorMethod<[], bigint>,
  'generateReferralCode' : ActorMethod<[string], string>,
  'getAllMintedIds' : ActorMethod<[], Array<PrydoIdWithPhoto>>,
  'getAllMintedIdsWithTokenIds' : ActorMethod<[], Array<PrydoIdWithTokenId>>,
  'getFraudFlags' : ActorMethod<[], Array<FraudFlag>>,
  'getIdByWallet' : ActorMethod<[string], PrydoIdWithPhoto>,
  'getIdCount' : ActorMethod<[], bigint>,
  'getLivenessStatus' : ActorMethod<[string], LivenessStatus>,
  /**
   * / Look up a wallet's mint info: tokenId, ICRC-3 blockIndex, mintTimestamp.
   * / Returns null if the wallet has never minted a Prydo ID.
   */
  'getMintInfoByWallet' : ActorMethod<[string], [] | [MintInfo]>,
  /**
   * / Returns total minted supply (tokenCounter). Alias for icrc7_total_supply.
   */
  'getMintedCount' : ActorMethod<[], bigint>,
  'getReferralsByWallet' : ActorMethod<[string], Array<ReferralRecord>>,
  'getVerificationStatus' : ActorMethod<[string], VerificationRecord>,
  'icrc3_get_blocks' : ActorMethod<
    [Array<{ 'start' : bigint, 'length' : bigint }>],
    {
      'log_length' : bigint,
      'blocks' : Array<{ 'id' : bigint, 'block' : Value }>,
      'archived_blocks' : Array<ArchivedBlocksRange>,
    }
  >,
  'icrc3_get_tip_certificate' : ActorMethod<[], [] | [DataCertificate]>,
  'icrc3_supported_block_types' : ActorMethod<
    [],
    Array<{ 'url' : string, 'block_type' : string }>
  >,
  'icrc7_atomic_batch_transfers' : ActorMethod<[], [] | [boolean]>,
  'icrc7_balance_of' : ActorMethod<[Array<Account>], Array<bigint>>,
  'icrc7_collection_metadata' : ActorMethod<[], Array<[string, Value]>>,
  'icrc7_default_take_value' : ActorMethod<[], [] | [bigint]>,
  'icrc7_description' : ActorMethod<[], [] | [string]>,
  'icrc7_logo' : ActorMethod<[], [] | [string]>,
  'icrc7_max_memo_size' : ActorMethod<[], [] | [bigint]>,
  'icrc7_max_query_batch_size' : ActorMethod<[], [] | [bigint]>,
  'icrc7_max_take_value' : ActorMethod<[], [] | [bigint]>,
  'icrc7_max_update_batch_size' : ActorMethod<[], [] | [bigint]>,
  'icrc7_name' : ActorMethod<[], string>,
  'icrc7_owner_of' : ActorMethod<[Array<bigint>], Array<[] | [Account]>>,
  'icrc7_supply_cap' : ActorMethod<[], [] | [bigint]>,
  'icrc7_symbol' : ActorMethod<[], string>,
  'icrc7_token_metadata' : ActorMethod<
    [Array<bigint>],
    Array<[] | [Array<[string, Value]>]>
  >,
  'icrc7_tokens' : ActorMethod<[[] | [bigint], [] | [bigint]], Array<bigint>>,
  'icrc7_tokens_of' : ActorMethod<
    [Account, [] | [bigint], [] | [bigint]],
    Array<bigint>
  >,
  'icrc7_total_supply' : ActorMethod<[], bigint>,
  /**
   * / Minimal transfer stub — transfers are not intended in Prydo but required for ICRC-7 compliance.
   */
  'icrc7_transfer' : ActorMethod<
    [Array<TransferArg>],
    Array<[] | [TransferResult]>
  >,
  /**
   * / Mint a Prydo ID. Requires a PASS verification for the wallet.
   */
  'mintId' : ActorMethod<
    [string, string, string, [] | [ExternalBlob]],
    MintOutput
  >,
  'reVerifyIdentity' : ActorMethod<[string], string>,
  'removeId' : ActorMethod<[string], boolean>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'updateFlagStatus' : ActorMethod<[string, string, bigint, string], boolean>,
  'uploadPhoto' : ActorMethod<[string, ExternalBlob], PrydoIdWithPhoto>,
  'verifyIdentity' : ActorMethod<
    [string, string, string, IdDocumentType, Array<[string, boolean]>],
    VerificationResult
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];