/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface FraudFlag {
    status: string;
    refereeWallet: string;
    flagReason: string;
    timestamp: bigint;
    severity: string;
    referrerWallet: string;
}
export interface Account {
    owner: Principal;
    subaccount?: Uint8Array;
}
export interface TransformationOutput {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export interface DataCertificate {
    certificate: Uint8Array;
    hash_tree: Uint8Array;
}
export interface _ImmutableObjectStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export interface PrydoIdWithTokenId {
    tokenId?: bigint;
    photo?: ExternalBlob;
    idRecord: PrydoIdRecord;
}
export interface PrydoIdWithPhoto {
    photo?: ExternalBlob;
    idRecord: PrydoIdRecord;
}
export type TransferResult = {
    __kind__: "Ok";
    Ok: bigint;
} | {
    __kind__: "Err";
    Err: TransferError;
};
export interface TransformationInput {
    context: Uint8Array;
    response: http_request_result;
}
export interface ArchivedBlocksRange {
    start: bigint;
    length: bigint;
}
export interface VerificationRecord {
    status: VerificationStatus;
    liveness_retry_count?: bigint;
    liveness_attempts?: Array<LivenessAttempt>;
    id_document_type?: IdDocumentType;
    error_reason?: string;
    liveness_cooldown_until?: bigint;
    verified_at: bigint;
    wallet: string;
}
export type Value = {
    __kind__: "Int";
    Int: bigint;
} | {
    __kind__: "Map";
    Map: Array<[string, Value]>;
} | {
    __kind__: "Nat";
    Nat: bigint;
} | {
    __kind__: "Blob";
    Blob: Uint8Array;
} | {
    __kind__: "Bool";
    Bool: boolean;
} | {
    __kind__: "Text";
    Text: string;
} | {
    __kind__: "Array";
    Array: Array<Value>;
};
export interface MintOutput {
    idCount: bigint;
    record: PrydoIdWithPhoto;
}
export interface _ImmutableObjectStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface MintInfo {
    tokenId: bigint;
    mintTimestamp: bigint;
    blockIndex: bigint;
    wallet: string;
}
export interface LivenessStatus {
    cooldown_until?: bigint;
    retry_count: bigint;
    attempts: Array<LivenessAttempt>;
}
export interface _ImmutableObjectStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface LivenessAttempt {
    attempted_at: bigint;
    passed: boolean;
    challenge_type: ChallengeType;
}
export interface http_header {
    value: string;
    name: string;
}
export interface http_request_result {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export type VerificationResult = {
    __kind__: "ok";
    ok: VerificationRecord;
} | {
    __kind__: "err";
    err: string;
};
export interface TransferArg {
    to: Account;
    token_id: bigint;
    memo?: Uint8Array;
    from_subaccount?: Uint8Array;
    created_at_time?: bigint;
}
export interface ReferralRecord {
    referrer: string;
    blockId: bigint;
    timestamp: bigint;
    ipHash: string;
    deviceHash: string;
    referee: string;
}
export interface PrydoIdRecord {
    avatarType: string;
    tier: string;
    timestamp: bigint;
    wallet: string;
}
export type TransferError = {
    __kind__: "GenericError";
    GenericError: {
        message: string;
        error_code: bigint;
    };
} | {
    __kind__: "Duplicate";
    Duplicate: {
        duplicate_of: bigint;
    };
} | {
    __kind__: "NonExistingTokenId";
    NonExistingTokenId: null;
} | {
    __kind__: "Unauthorized";
    Unauthorized: null;
} | {
    __kind__: "CreatedInFuture";
    CreatedInFuture: {
        ledger_time: bigint;
    };
} | {
    __kind__: "InvalidRecipient";
    InvalidRecipient: null;
} | {
    __kind__: "GenericBatchError";
    GenericBatchError: {
        message: string;
        error_code: bigint;
    };
} | {
    __kind__: "TooOld";
    TooOld: null;
};
export enum ChallengeType {
    smile = "smile",
    blink = "blink"
}
export enum IdDocumentType {
    Passport = "Passport",
    Aadhaar = "Aadhaar",
    DriversLicense = "DriversLicense",
    NationalId = "NationalId"
}
export enum VerificationStatus {
    FAIL = "FAIL",
    PASS = "PASS",
    UNVERIFIED = "UNVERIFIED",
    PENDING = "PENDING"
}
export interface backendInterface {
    _immutableObjectStorageBlobsAreLive(hashes: Array<Uint8Array>): Promise<Array<boolean>>;
    _immutableObjectStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _immutableObjectStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _immutableObjectStorageCreateCertificate(blobHash: string): Promise<_ImmutableObjectStorageCreateCertificateResult>;
    _immutableObjectStorageRefillCashier(refillInformation: _ImmutableObjectStorageRefillInformation | null): Promise<_ImmutableObjectStorageRefillResult>;
    _immutableObjectStorageUpdateGatewayPrincipals(): Promise<void>;
    addReferral(referrer: string, referee: string, ipHash: string, deviceHash: string): Promise<void>;
    clearAllIds(): Promise<bigint>;
    generateReferralCode(wallet: string): Promise<string>;
    getAllMintedIds(): Promise<Array<PrydoIdWithPhoto>>;
    getAllMintedIdsWithTokenIds(): Promise<Array<PrydoIdWithTokenId>>;
    getFraudFlags(): Promise<Array<FraudFlag>>;
    getIdByWallet(wallet: string): Promise<PrydoIdWithPhoto>;
    getIdCount(): Promise<bigint>;
    getLivenessStatus(wallet: string): Promise<LivenessStatus>;
    /**
     * / Look up a wallet's mint info: tokenId, ICRC-3 blockIndex, mintTimestamp.
     * / Returns null if the wallet has never minted a Prydo ID.
     */
    getMintInfoByWallet(wallet: string): Promise<MintInfo | null>;
    /**
     * / Returns total minted supply (tokenCounter). Alias for icrc7_total_supply.
     */
    getMintedCount(): Promise<bigint>;
    getReferralsByWallet(wallet: string): Promise<Array<ReferralRecord>>;
    getVerificationStatus(wallet: string): Promise<VerificationRecord>;
    icrc3_get_blocks(args: Array<{
        start: bigint;
        length: bigint;
    }>): Promise<{
        log_length: bigint;
        blocks: Array<{
            id: bigint;
            block: Value;
        }>;
        archived_blocks: Array<ArchivedBlocksRange>;
    }>;
    icrc3_get_tip_certificate(): Promise<DataCertificate | null>;
    icrc3_supported_block_types(): Promise<Array<{
        url: string;
        block_type: string;
    }>>;
    icrc7_atomic_batch_transfers(): Promise<boolean | null>;
    icrc7_balance_of(accounts: Array<Account>): Promise<Array<bigint>>;
    icrc7_collection_metadata(): Promise<Array<[string, Value]>>;
    icrc7_default_take_value(): Promise<bigint | null>;
    icrc7_description(): Promise<string | null>;
    icrc7_logo(): Promise<string | null>;
    icrc7_max_memo_size(): Promise<bigint | null>;
    icrc7_max_query_batch_size(): Promise<bigint | null>;
    icrc7_max_take_value(): Promise<bigint | null>;
    icrc7_max_update_batch_size(): Promise<bigint | null>;
    icrc7_name(): Promise<string>;
    icrc7_owner_of(token_ids: Array<bigint>): Promise<Array<Account | null>>;
    icrc7_supply_cap(): Promise<bigint | null>;
    icrc7_symbol(): Promise<string>;
    icrc7_token_metadata(token_ids: Array<bigint>): Promise<Array<Array<[string, Value]> | null>>;
    icrc7_tokens(prev: bigint | null, take: bigint | null): Promise<Array<bigint>>;
    icrc7_tokens_of(account: Account, prev: bigint | null, take: bigint | null): Promise<Array<bigint>>;
    icrc7_total_supply(): Promise<bigint>;
    /**
     * / Minimal transfer stub — transfers are not intended in Prydo but required for ICRC-7 compliance.
     */
    icrc7_transfer(args: Array<TransferArg>): Promise<Array<TransferResult | null>>;
    /**
     * / Mint a Prydo ID. Requires a PASS verification for the wallet.
     */
    mintId(wallet: string, tier: string, avatarType: string, photo: ExternalBlob | null): Promise<MintOutput>;
    reVerifyIdentity(wallet: string): Promise<string>;
    removeId(wallet: string): Promise<boolean>;
    transform(input: TransformationInput): Promise<TransformationOutput>;
    updateFlagStatus(referrerWallet: string, refereeWallet: string, timestamp: bigint, newStatus: string): Promise<boolean>;
    uploadPhoto(wallet: string, photo: ExternalBlob): Promise<PrydoIdWithPhoto>;
    verifyIdentity(wallet: string, id_image_url: string, selfie_image_url: string, idDocumentType: IdDocumentType, liveness_results: Array<[string, boolean]>): Promise<VerificationResult>;
}
import type { Account as _Account, ArchivedBlocksRange as _ArchivedBlocksRange, ChallengeType as _ChallengeType, DataCertificate as _DataCertificate, ExternalBlob as _ExternalBlob, IdDocumentType as _IdDocumentType, LivenessAttempt as _LivenessAttempt, LivenessStatus as _LivenessStatus, MintInfo as _MintInfo, MintOutput as _MintOutput, PrydoIdRecord as _PrydoIdRecord, PrydoIdWithPhoto as _PrydoIdWithPhoto, PrydoIdWithTokenId as _PrydoIdWithTokenId, TransferArg as _TransferArg, TransferError as _TransferError, TransferResult as _TransferResult, Value as _Value, VerificationRecord as _VerificationRecord, VerificationResult as _VerificationResult, VerificationStatus as _VerificationStatus, _ImmutableObjectStorageRefillInformation as __ImmutableObjectStorageRefillInformation, _ImmutableObjectStorageRefillResult as __ImmutableObjectStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _immutableObjectStorageBlobsAreLive(arg0: Array<Uint8Array>): Promise<Array<boolean>> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageBlobsAreLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageBlobsAreLive(arg0);
            return result;
        }
    }
    async _immutableObjectStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageBlobsToDelete();
            return result;
        }
    }
    async _immutableObjectStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _immutableObjectStorageCreateCertificate(arg0: string): Promise<_ImmutableObjectStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _immutableObjectStorageRefillCashier(arg0: _ImmutableObjectStorageRefillInformation | null): Promise<_ImmutableObjectStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__ImmutableObjectStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__ImmutableObjectStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _immutableObjectStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async addReferral(arg0: string, arg1: string, arg2: string, arg3: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addReferral(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addReferral(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async clearAllIds(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.clearAllIds();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.clearAllIds();
            return result;
        }
    }
    async generateReferralCode(arg0: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.generateReferralCode(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.generateReferralCode(arg0);
            return result;
        }
    }
    async getAllMintedIds(): Promise<Array<PrydoIdWithPhoto>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllMintedIds();
                return from_candid_vec_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllMintedIds();
            return from_candid_vec_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllMintedIdsWithTokenIds(): Promise<Array<PrydoIdWithTokenId>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllMintedIdsWithTokenIds();
                return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllMintedIdsWithTokenIds();
            return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async getFraudFlags(): Promise<Array<FraudFlag>> {
        if (this.processError) {
            try {
                const result = await this.actor.getFraudFlags();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFraudFlags();
            return result;
        }
    }
    async getIdByWallet(arg0: string): Promise<PrydoIdWithPhoto> {
        if (this.processError) {
            try {
                const result = await this.actor.getIdByWallet(arg0);
                return from_candid_PrydoIdWithPhoto_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getIdByWallet(arg0);
            return from_candid_PrydoIdWithPhoto_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async getIdCount(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getIdCount();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getIdCount();
            return result;
        }
    }
    async getLivenessStatus(arg0: string): Promise<LivenessStatus> {
        if (this.processError) {
            try {
                const result = await this.actor.getLivenessStatus(arg0);
                return from_candid_LivenessStatus_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLivenessStatus(arg0);
            return from_candid_LivenessStatus_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMintInfoByWallet(arg0: string): Promise<MintInfo | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMintInfoByWallet(arg0);
                return from_candid_opt_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMintInfoByWallet(arg0);
            return from_candid_opt_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMintedCount(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getMintedCount();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMintedCount();
            return result;
        }
    }
    async getReferralsByWallet(arg0: string): Promise<Array<ReferralRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getReferralsByWallet(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getReferralsByWallet(arg0);
            return result;
        }
    }
    async getVerificationStatus(arg0: string): Promise<VerificationRecord> {
        if (this.processError) {
            try {
                const result = await this.actor.getVerificationStatus(arg0);
                return from_candid_VerificationRecord_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getVerificationStatus(arg0);
            return from_candid_VerificationRecord_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async icrc3_get_blocks(arg0: Array<{
        start: bigint;
        length: bigint;
    }>): Promise<{
        log_length: bigint;
        blocks: Array<{
            id: bigint;
            block: Value;
        }>;
        archived_blocks: Array<ArchivedBlocksRange>;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.icrc3_get_blocks(arg0);
                return from_candid_record_n34(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.icrc3_get_blocks(arg0);
            return from_candid_record_n34(this._uploadFile, this._downloadFile, result);
        }
    }
    async icrc3_get_tip_certificate(): Promise<DataCertificate | null> {
        if (this.processError) {
            try {
                const result = await this.actor.icrc3_get_tip_certificate();
                return from_candid_opt_n42(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.icrc3_get_tip_certificate();
            return from_candid_opt_n42(this._uploadFile, this._downloadFile, result);
        }
    }
    async icrc3_supported_block_types(): Promise<Array<{
        url: string;
        block_type: string;
    }>> {
        if (this.processError) {
            try {
                const result = await this.actor.icrc3_supported_block_types();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.icrc3_supported_block_types();
            return result;
        }
    }
    async icrc7_atomic_batch_transfers(): Promise<boolean | null> {
        if (this.processError) {
            try {
                const result = await this.actor.icrc7_atomic_batch_transfers();
                return from_candid_opt_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.icrc7_atomic_batch_transfers();
            return from_candid_opt_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async icrc7_balance_of(arg0: Array<Account>): Promise<Array<bigint>> {
        if (this.processError) {
            try {
                const result = await this.actor.icrc7_balance_of(to_candid_vec_n43(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.icrc7_balance_of(to_candid_vec_n43(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async icrc7_collection_metadata(): Promise<Array<[string, Value]>> {
        if (this.processError) {
            try {
                const result = await this.actor.icrc7_collection_metadata();
                return from_candid_vec_n39(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.icrc7_collection_metadata();
            return from_candid_vec_n39(this._uploadFile, this._downloadFile, result);
        }
    }
    async icrc7_default_take_value(): Promise<bigint | null> {
        if (this.processError) {
            try {
                const result = await this.actor.icrc7_default_take_value();
                return from_candid_opt_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.icrc7_default_take_value();
            return from_candid_opt_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async icrc7_description(): Promise<string | null> {
        if (this.processError) {
            try {
                const result = await this.actor.icrc7_description();
                return from_candid_opt_n33(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.icrc7_description();
            return from_candid_opt_n33(this._uploadFile, this._downloadFile, result);
        }
    }
    async icrc7_logo(): Promise<string | null> {
        if (this.processError) {
            try {
                const result = await this.actor.icrc7_logo();
                return from_candid_opt_n33(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.icrc7_logo();
            return from_candid_opt_n33(this._uploadFile, this._downloadFile, result);
        }
    }
    async icrc7_max_memo_size(): Promise<bigint | null> {
        if (this.processError) {
            try {
                const result = await this.actor.icrc7_max_memo_size();
                return from_candid_opt_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.icrc7_max_memo_size();
            return from_candid_opt_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async icrc7_max_query_batch_size(): Promise<bigint | null> {
        if (this.processError) {
            try {
                const result = await this.actor.icrc7_max_query_batch_size();
                return from_candid_opt_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.icrc7_max_query_batch_size();
            return from_candid_opt_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async icrc7_max_take_value(): Promise<bigint | null> {
        if (this.processError) {
            try {
                const result = await this.actor.icrc7_max_take_value();
                return from_candid_opt_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.icrc7_max_take_value();
            return from_candid_opt_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async icrc7_max_update_batch_size(): Promise<bigint | null> {
        if (this.processError) {
            try {
                const result = await this.actor.icrc7_max_update_batch_size();
                return from_candid_opt_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.icrc7_max_update_batch_size();
            return from_candid_opt_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async icrc7_name(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.icrc7_name();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.icrc7_name();
            return result;
        }
    }
    async icrc7_owner_of(arg0: Array<bigint>): Promise<Array<Account | null>> {
        if (this.processError) {
            try {
                const result = await this.actor.icrc7_owner_of(arg0);
                return from_candid_vec_n46(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.icrc7_owner_of(arg0);
            return from_candid_vec_n46(this._uploadFile, this._downloadFile, result);
        }
    }
    async icrc7_supply_cap(): Promise<bigint | null> {
        if (this.processError) {
            try {
                const result = await this.actor.icrc7_supply_cap();
                return from_candid_opt_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.icrc7_supply_cap();
            return from_candid_opt_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async icrc7_symbol(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.icrc7_symbol();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.icrc7_symbol();
            return result;
        }
    }
    async icrc7_token_metadata(arg0: Array<bigint>): Promise<Array<Array<[string, Value]> | null>> {
        if (this.processError) {
            try {
                const result = await this.actor.icrc7_token_metadata(arg0);
                return from_candid_vec_n51(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.icrc7_token_metadata(arg0);
            return from_candid_vec_n51(this._uploadFile, this._downloadFile, result);
        }
    }
    async icrc7_tokens(arg0: bigint | null, arg1: bigint | null): Promise<Array<bigint>> {
        if (this.processError) {
            try {
                const result = await this.actor.icrc7_tokens(to_candid_opt_n53(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n53(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.icrc7_tokens(to_candid_opt_n53(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n53(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async icrc7_tokens_of(arg0: Account, arg1: bigint | null, arg2: bigint | null): Promise<Array<bigint>> {
        if (this.processError) {
            try {
                const result = await this.actor.icrc7_tokens_of(to_candid_Account_n44(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n53(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n53(this._uploadFile, this._downloadFile, arg2));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.icrc7_tokens_of(to_candid_Account_n44(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n53(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n53(this._uploadFile, this._downloadFile, arg2));
            return result;
        }
    }
    async icrc7_total_supply(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.icrc7_total_supply();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.icrc7_total_supply();
            return result;
        }
    }
    async icrc7_transfer(arg0: Array<TransferArg>): Promise<Array<TransferResult | null>> {
        if (this.processError) {
            try {
                const result = await this.actor.icrc7_transfer(to_candid_vec_n54(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n57(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.icrc7_transfer(to_candid_vec_n54(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n57(this._uploadFile, this._downloadFile, result);
        }
    }
    async mintId(arg0: string, arg1: string, arg2: string, arg3: ExternalBlob | null): Promise<MintOutput> {
        if (this.processError) {
            try {
                const result = await this.actor.mintId(arg0, arg1, arg2, await to_candid_opt_n63(this._uploadFile, this._downloadFile, arg3));
                return from_candid_MintOutput_n65(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.mintId(arg0, arg1, arg2, await to_candid_opt_n63(this._uploadFile, this._downloadFile, arg3));
            return from_candid_MintOutput_n65(this._uploadFile, this._downloadFile, result);
        }
    }
    async reVerifyIdentity(arg0: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.reVerifyIdentity(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.reVerifyIdentity(arg0);
            return result;
        }
    }
    async removeId(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.removeId(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeId(arg0);
            return result;
        }
    }
    async transform(arg0: TransformationInput): Promise<TransformationOutput> {
        if (this.processError) {
            try {
                const result = await this.actor.transform(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.transform(arg0);
            return result;
        }
    }
    async updateFlagStatus(arg0: string, arg1: string, arg2: bigint, arg3: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateFlagStatus(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateFlagStatus(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async uploadPhoto(arg0: string, arg1: ExternalBlob): Promise<PrydoIdWithPhoto> {
        if (this.processError) {
            try {
                const result = await this.actor.uploadPhoto(arg0, await to_candid_ExternalBlob_n64(this._uploadFile, this._downloadFile, arg1));
                return from_candid_PrydoIdWithPhoto_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.uploadPhoto(arg0, await to_candid_ExternalBlob_n64(this._uploadFile, this._downloadFile, arg1));
            return from_candid_PrydoIdWithPhoto_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async verifyIdentity(arg0: string, arg1: string, arg2: string, arg3: IdDocumentType, arg4: Array<[string, boolean]>): Promise<VerificationResult> {
        if (this.processError) {
            try {
                const result = await this.actor.verifyIdentity(arg0, arg1, arg2, to_candid_IdDocumentType_n67(this._uploadFile, this._downloadFile, arg3), arg4);
                return from_candid_VerificationResult_n69(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.verifyIdentity(arg0, arg1, arg2, to_candid_IdDocumentType_n67(this._uploadFile, this._downloadFile, arg3), arg4);
            return from_candid_VerificationResult_n69(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_Account_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Account): Account {
    return from_candid_record_n49(_uploadFile, _downloadFile, value);
}
function from_candid_ChallengeType_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ChallengeType): ChallengeType {
    return from_candid_variant_n23(_uploadFile, _downloadFile, value);
}
async function from_candid_ExternalBlob_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await _downloadFile(value);
}
function from_candid_IdDocumentType_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _IdDocumentType): IdDocumentType {
    return from_candid_variant_n32(_uploadFile, _downloadFile, value);
}
function from_candid_LivenessAttempt_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _LivenessAttempt): LivenessAttempt {
    return from_candid_record_n21(_uploadFile, _downloadFile, value);
}
function from_candid_LivenessStatus_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _LivenessStatus): LivenessStatus {
    return from_candid_record_n17(_uploadFile, _downloadFile, value);
}
async function from_candid_MintOutput_n65(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MintOutput): Promise<MintOutput> {
    return await from_candid_record_n66(_uploadFile, _downloadFile, value);
}
async function from_candid_PrydoIdWithPhoto_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PrydoIdWithPhoto): Promise<PrydoIdWithPhoto> {
    return await from_candid_record_n10(_uploadFile, _downloadFile, value);
}
async function from_candid_PrydoIdWithTokenId_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PrydoIdWithTokenId): Promise<PrydoIdWithTokenId> {
    return await from_candid_record_n15(_uploadFile, _downloadFile, value);
}
function from_candid_TransferError_n61(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TransferError): TransferError {
    return from_candid_variant_n62(_uploadFile, _downloadFile, value);
}
function from_candid_TransferResult_n59(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TransferResult): TransferResult {
    return from_candid_variant_n60(_uploadFile, _downloadFile, value);
}
function from_candid_Value_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Value): Value {
    return from_candid_variant_n38(_uploadFile, _downloadFile, value);
}
function from_candid_VerificationRecord_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _VerificationRecord): VerificationRecord {
    return from_candid_record_n26(_uploadFile, _downloadFile, value);
}
function from_candid_VerificationResult_n69(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _VerificationResult): VerificationResult {
    return from_candid_variant_n70(_uploadFile, _downloadFile, value);
}
function from_candid_VerificationStatus_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _VerificationStatus): VerificationStatus {
    return from_candid_variant_n28(_uploadFile, _downloadFile, value);
}
function from_candid__ImmutableObjectStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __ImmutableObjectStorageRefillResult): _ImmutableObjectStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
async function from_candid_opt_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ExternalBlob]): Promise<ExternalBlob | null> {
    return value.length === 0 ? null : await from_candid_ExternalBlob_n12(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_MintInfo]): MintInfo | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [Array<_LivenessAttempt>]): Array<LivenessAttempt> | null {
    return value.length === 0 ? null : from_candid_vec_n19(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_IdDocumentType]): IdDocumentType | null {
    return value.length === 0 ? null : from_candid_IdDocumentType_n31(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_DataCertificate]): DataCertificate | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Account]): Account | null {
    return value.length === 0 ? null : from_candid_Account_n48(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [Uint8Array]): Uint8Array | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [Array<[string, _Value]>]): Array<[string, Value]> | null {
    return value.length === 0 ? null : from_candid_vec_n39(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n58(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_TransferResult]): TransferResult | null {
    return value.length === 0 ? null : from_candid_TransferResult_n59(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_record_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    photo: [] | [_ExternalBlob];
    idRecord: _PrydoIdRecord;
}): Promise<{
    photo?: ExternalBlob;
    idRecord: PrydoIdRecord;
}> {
    return {
        photo: record_opt_to_undefined(await from_candid_opt_n11(_uploadFile, _downloadFile, value.photo)),
        idRecord: value.idRecord
    };
}
async function from_candid_record_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    tokenId: [] | [bigint];
    photo: [] | [_ExternalBlob];
    idRecord: _PrydoIdRecord;
}): Promise<{
    tokenId?: bigint;
    photo?: ExternalBlob;
    idRecord: PrydoIdRecord;
}> {
    return {
        tokenId: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.tokenId)),
        photo: record_opt_to_undefined(await from_candid_opt_n11(_uploadFile, _downloadFile, value.photo)),
        idRecord: value.idRecord
    };
}
function from_candid_record_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    cooldown_until: [] | [bigint];
    retry_count: bigint;
    attempts: Array<_LivenessAttempt>;
}): {
    cooldown_until?: bigint;
    retry_count: bigint;
    attempts: Array<LivenessAttempt>;
} {
    return {
        cooldown_until: record_opt_to_undefined(from_candid_opt_n18(_uploadFile, _downloadFile, value.cooldown_until)),
        retry_count: value.retry_count,
        attempts: from_candid_vec_n19(_uploadFile, _downloadFile, value.attempts)
    };
}
function from_candid_record_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    attempted_at: bigint;
    passed: boolean;
    challenge_type: _ChallengeType;
}): {
    attempted_at: bigint;
    passed: boolean;
    challenge_type: ChallengeType;
} {
    return {
        attempted_at: value.attempted_at,
        passed: value.passed,
        challenge_type: from_candid_ChallengeType_n22(_uploadFile, _downloadFile, value.challenge_type)
    };
}
function from_candid_record_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: _VerificationStatus;
    liveness_retry_count: [] | [bigint];
    liveness_attempts: [] | [Array<_LivenessAttempt>];
    id_document_type: [] | [_IdDocumentType];
    error_reason: [] | [string];
    liveness_cooldown_until: [] | [bigint];
    verified_at: bigint;
    wallet: string;
}): {
    status: VerificationStatus;
    liveness_retry_count?: bigint;
    liveness_attempts?: Array<LivenessAttempt>;
    id_document_type?: IdDocumentType;
    error_reason?: string;
    liveness_cooldown_until?: bigint;
    verified_at: bigint;
    wallet: string;
} {
    return {
        status: from_candid_VerificationStatus_n27(_uploadFile, _downloadFile, value.status),
        liveness_retry_count: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.liveness_retry_count)),
        liveness_attempts: record_opt_to_undefined(from_candid_opt_n29(_uploadFile, _downloadFile, value.liveness_attempts)),
        id_document_type: record_opt_to_undefined(from_candid_opt_n30(_uploadFile, _downloadFile, value.id_document_type)),
        error_reason: record_opt_to_undefined(from_candid_opt_n33(_uploadFile, _downloadFile, value.error_reason)),
        liveness_cooldown_until: record_opt_to_undefined(from_candid_opt_n18(_uploadFile, _downloadFile, value.liveness_cooldown_until)),
        verified_at: value.verified_at,
        wallet: value.wallet
    };
}
function from_candid_record_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    log_length: bigint;
    blocks: Array<{
        id: bigint;
        block: _Value;
    }>;
    archived_blocks: Array<_ArchivedBlocksRange>;
}): {
    log_length: bigint;
    blocks: Array<{
        id: bigint;
        block: Value;
    }>;
    archived_blocks: Array<ArchivedBlocksRange>;
} {
    return {
        log_length: value.log_length,
        blocks: from_candid_vec_n35(_uploadFile, _downloadFile, value.blocks),
        archived_blocks: value.archived_blocks
    };
}
function from_candid_record_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    block: _Value;
}): {
    id: bigint;
    block: Value;
} {
    return {
        id: value.id,
        block: from_candid_Value_n37(_uploadFile, _downloadFile, value.block)
    };
}
function from_candid_record_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    owner: Principal;
    subaccount: [] | [Uint8Array];
}): {
    owner: Principal;
    subaccount?: Uint8Array;
} {
    return {
        owner: value.owner,
        subaccount: record_opt_to_undefined(from_candid_opt_n50(_uploadFile, _downloadFile, value.subaccount))
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
async function from_candid_record_n66(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    idCount: bigint;
    record: _PrydoIdWithPhoto;
}): Promise<{
    idCount: bigint;
    record: PrydoIdWithPhoto;
}> {
    return {
        idCount: value.idCount,
        record: await from_candid_PrydoIdWithPhoto_n9(_uploadFile, _downloadFile, value.record)
    };
}
function from_candid_tuple_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [string, _Value]): [string, Value] {
    return [
        value[0],
        from_candid_Value_n37(_uploadFile, _downloadFile, value[1])
    ];
}
function from_candid_variant_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    smile: null;
} | {
    blink: null;
}): ChallengeType {
    return "smile" in value ? ChallengeType.smile : "blink" in value ? ChallengeType.blink : value;
}
function from_candid_variant_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    FAIL: null;
} | {
    PASS: null;
} | {
    UNVERIFIED: null;
} | {
    PENDING: null;
}): VerificationStatus {
    return "FAIL" in value ? VerificationStatus.FAIL : "PASS" in value ? VerificationStatus.PASS : "UNVERIFIED" in value ? VerificationStatus.UNVERIFIED : "PENDING" in value ? VerificationStatus.PENDING : value;
}
function from_candid_variant_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Passport: null;
} | {
    Aadhaar: null;
} | {
    DriversLicense: null;
} | {
    NationalId: null;
}): IdDocumentType {
    return "Passport" in value ? IdDocumentType.Passport : "Aadhaar" in value ? IdDocumentType.Aadhaar : "DriversLicense" in value ? IdDocumentType.DriversLicense : "NationalId" in value ? IdDocumentType.NationalId : value;
}
function from_candid_variant_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Int: bigint;
} | {
    Map: Array<[string, _Value]>;
} | {
    Nat: bigint;
} | {
    Blob: Uint8Array;
} | {
    Bool: boolean;
} | {
    Text: string;
} | {
    Array: Array<_Value>;
}): {
    __kind__: "Int";
    Int: bigint;
} | {
    __kind__: "Map";
    Map: Array<[string, Value]>;
} | {
    __kind__: "Nat";
    Nat: bigint;
} | {
    __kind__: "Blob";
    Blob: Uint8Array;
} | {
    __kind__: "Bool";
    Bool: boolean;
} | {
    __kind__: "Text";
    Text: string;
} | {
    __kind__: "Array";
    Array: Array<Value>;
} {
    return "Int" in value ? {
        __kind__: "Int",
        Int: value.Int
    } : "Map" in value ? {
        __kind__: "Map",
        Map: from_candid_vec_n39(_uploadFile, _downloadFile, value.Map)
    } : "Nat" in value ? {
        __kind__: "Nat",
        Nat: value.Nat
    } : "Blob" in value ? {
        __kind__: "Blob",
        Blob: value.Blob
    } : "Bool" in value ? {
        __kind__: "Bool",
        Bool: value.Bool
    } : "Text" in value ? {
        __kind__: "Text",
        Text: value.Text
    } : "Array" in value ? {
        __kind__: "Array",
        Array: from_candid_vec_n41(_uploadFile, _downloadFile, value.Array)
    } : value;
}
function from_candid_variant_n60(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Ok: bigint;
} | {
    Err: _TransferError;
}): {
    __kind__: "Ok";
    Ok: bigint;
} | {
    __kind__: "Err";
    Err: TransferError;
} {
    return "Ok" in value ? {
        __kind__: "Ok",
        Ok: value.Ok
    } : "Err" in value ? {
        __kind__: "Err",
        Err: from_candid_TransferError_n61(_uploadFile, _downloadFile, value.Err)
    } : value;
}
function from_candid_variant_n62(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    GenericError: {
        message: string;
        error_code: bigint;
    };
} | {
    Duplicate: {
        duplicate_of: bigint;
    };
} | {
    NonExistingTokenId: null;
} | {
    Unauthorized: null;
} | {
    CreatedInFuture: {
        ledger_time: bigint;
    };
} | {
    InvalidRecipient: null;
} | {
    GenericBatchError: {
        message: string;
        error_code: bigint;
    };
} | {
    TooOld: null;
}): {
    __kind__: "GenericError";
    GenericError: {
        message: string;
        error_code: bigint;
    };
} | {
    __kind__: "Duplicate";
    Duplicate: {
        duplicate_of: bigint;
    };
} | {
    __kind__: "NonExistingTokenId";
    NonExistingTokenId: null;
} | {
    __kind__: "Unauthorized";
    Unauthorized: null;
} | {
    __kind__: "CreatedInFuture";
    CreatedInFuture: {
        ledger_time: bigint;
    };
} | {
    __kind__: "InvalidRecipient";
    InvalidRecipient: null;
} | {
    __kind__: "GenericBatchError";
    GenericBatchError: {
        message: string;
        error_code: bigint;
    };
} | {
    __kind__: "TooOld";
    TooOld: null;
} {
    return "GenericError" in value ? {
        __kind__: "GenericError",
        GenericError: value.GenericError
    } : "Duplicate" in value ? {
        __kind__: "Duplicate",
        Duplicate: value.Duplicate
    } : "NonExistingTokenId" in value ? {
        __kind__: "NonExistingTokenId",
        NonExistingTokenId: value.NonExistingTokenId
    } : "Unauthorized" in value ? {
        __kind__: "Unauthorized",
        Unauthorized: value.Unauthorized
    } : "CreatedInFuture" in value ? {
        __kind__: "CreatedInFuture",
        CreatedInFuture: value.CreatedInFuture
    } : "InvalidRecipient" in value ? {
        __kind__: "InvalidRecipient",
        InvalidRecipient: value.InvalidRecipient
    } : "GenericBatchError" in value ? {
        __kind__: "GenericBatchError",
        GenericBatchError: value.GenericBatchError
    } : "TooOld" in value ? {
        __kind__: "TooOld",
        TooOld: value.TooOld
    } : value;
}
function from_candid_variant_n70(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _VerificationRecord;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: VerificationRecord;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_VerificationRecord_n25(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
async function from_candid_vec_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_PrydoIdWithTokenId>): Promise<Array<PrydoIdWithTokenId>> {
    return await Promise.all(value.map(async (x)=>await from_candid_PrydoIdWithTokenId_n14(_uploadFile, _downloadFile, x)));
}
function from_candid_vec_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_LivenessAttempt>): Array<LivenessAttempt> {
    return value.map((x)=>from_candid_LivenessAttempt_n20(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<{
    id: bigint;
    block: _Value;
}>): Array<{
    id: bigint;
    block: Value;
}> {
    return value.map((x)=>from_candid_record_n36(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<[string, _Value]>): Array<[string, Value]> {
    return value.map((x)=>from_candid_tuple_n40(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Value>): Array<Value> {
    return value.map((x)=>from_candid_Value_n37(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<[] | [_Account]>): Array<Account | null> {
    return value.map((x)=>from_candid_opt_n47(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<[] | [Array<[string, _Value]>]>): Array<Array<[string, Value]> | null> {
    return value.map((x)=>from_candid_opt_n52(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n57(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<[] | [_TransferResult]>): Array<TransferResult | null> {
    return value.map((x)=>from_candid_opt_n58(_uploadFile, _downloadFile, x));
}
async function from_candid_vec_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_PrydoIdWithPhoto>): Promise<Array<PrydoIdWithPhoto>> {
    return await Promise.all(value.map(async (x)=>await from_candid_PrydoIdWithPhoto_n9(_uploadFile, _downloadFile, x)));
}
function to_candid_Account_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Account): _Account {
    return to_candid_record_n45(_uploadFile, _downloadFile, value);
}
async function to_candid_ExternalBlob_n64(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await _uploadFile(value);
}
function to_candid_IdDocumentType_n67(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: IdDocumentType): _IdDocumentType {
    return to_candid_variant_n68(_uploadFile, _downloadFile, value);
}
function to_candid_TransferArg_n55(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TransferArg): _TransferArg {
    return to_candid_record_n56(_uploadFile, _downloadFile, value);
}
function to_candid__ImmutableObjectStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ImmutableObjectStorageRefillInformation): __ImmutableObjectStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ImmutableObjectStorageRefillInformation | null): [] | [__ImmutableObjectStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__ImmutableObjectStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n53(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: bigint | null): [] | [bigint] {
    return value === null ? candid_none() : candid_some(value);
}
async function to_candid_opt_n63(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob | null): Promise<[] | [_ExternalBlob]> {
    return value === null ? candid_none() : candid_some(await to_candid_ExternalBlob_n64(_uploadFile, _downloadFile, value));
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_record_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    owner: Principal;
    subaccount?: Uint8Array;
}): {
    owner: Principal;
    subaccount: [] | [Uint8Array];
} {
    return {
        owner: value.owner,
        subaccount: value.subaccount ? candid_some(value.subaccount) : candid_none()
    };
}
function to_candid_record_n56(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    to: Account;
    token_id: bigint;
    memo?: Uint8Array;
    from_subaccount?: Uint8Array;
    created_at_time?: bigint;
}): {
    to: _Account;
    token_id: bigint;
    memo: [] | [Uint8Array];
    from_subaccount: [] | [Uint8Array];
    created_at_time: [] | [bigint];
} {
    return {
        to: to_candid_Account_n44(_uploadFile, _downloadFile, value.to),
        token_id: value.token_id,
        memo: value.memo ? candid_some(value.memo) : candid_none(),
        from_subaccount: value.from_subaccount ? candid_some(value.from_subaccount) : candid_none(),
        created_at_time: value.created_at_time ? candid_some(value.created_at_time) : candid_none()
    };
}
function to_candid_variant_n68(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: IdDocumentType): {
    Passport: null;
} | {
    Aadhaar: null;
} | {
    DriversLicense: null;
} | {
    NationalId: null;
} {
    return value == IdDocumentType.Passport ? {
        Passport: null
    } : value == IdDocumentType.Aadhaar ? {
        Aadhaar: null
    } : value == IdDocumentType.DriversLicense ? {
        DriversLicense: null
    } : value == IdDocumentType.NationalId ? {
        NationalId: null
    } : value;
}
function to_candid_vec_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<Account>): Array<_Account> {
    return value.map((x)=>to_candid_Account_n44(_uploadFile, _downloadFile, x));
}
function to_candid_vec_n54(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<TransferArg>): Array<_TransferArg> {
    return value.map((x)=>to_candid_TransferArg_n55(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
